---
name: Deploy Staging

on:
  workflow_run:
    workflows: CI
    branches: master
    types: completed
    
jobs:
  deploy-test-bsc:
    name: Deploy Staging BSC
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: staging-bsc

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo "Test Staging"

    #   - uses: './.github/actions/prepare-node'

    #   - uses: './.github/actions/deploy'
    #     with:
    #       ENV_NAME: staging-bsc
    #       CI_TOKEN: '${{ secrets.CI_TOKEN1 }}'
    #       HARDHAT_NETWORK: bsc
    #       MAINNET_PROVIDER_URL: '${{ vars.MAINNET_PROVIDER_URL }}'
    #       DEPLOYER_PRIVATE_KEY: '${{ secrets.DEPLOYER_PRIVATE_KEY }}'
    #       ETHERSCAN_APIKEY: '${{ secrets.ETHERSCAN_APIKEY }}'
    #       GNOSIS_SAFE_ADDRESS: '${{ vars.GNOSIS_SAFE_ADDRESS }}'
    #       GNOSIS_SAFE_SERVICE_URL: '${{ vars.GNOSIS_SAFE_SERVICE_URL }}'
